---
title: "LegosDataset"
author: "Ben Lehmann"
date: "2023-12-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#Load the Data

```{r}
colors = read.csv('~/Legos/colors.csv')
inventories = read.csv('~/Legos/inventories.csv')
inventory_parts = read.csv('~/Legos/inventory_parts.csv')
inventory_sets = read.csv('~/Legos/inventory_sets.csv')
part_categ = read.csv('~/Legos/part_categories.csv')
parts = read.csv('~/Legos/parts.csv')
sets = read.csv('~/Legos/sets.csv')
themes = read.csv('~/Legos/themes.csv')
```


#Load Packages

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)

```



```{r}
colr = colors$rgb
head(colors)
```



#Graph of the Transparency

```{r}
colors %>% group_by(is_trans) %>% summarize(c=n())%>%
ggplot(aes(x=is_trans,y=c,fill=is_trans))+geom_bar(stat="identity")+scale_fill_manual(values=c("red","blue"))
```



#Do parts and themes by year

```{r}
parts_year = sets%>%select(year,num_parts)%>%group_by(year)%>%summarise(avg_parts=mean(num_parts))
parts_year%>%ggplot(aes(x=year,y=avg_parts,group=1))+geom_line(size=0.5)+geom_point(color="blue",size=0.5)+labs(title="Average Parts per Year")
```


```{r}
sets %>%select(year,theme_id)%>%group_by(year)%>%summarise(theme_count=length(unique(theme_id)))%>%ggplot(aes(x=year,y=theme_count))+geom_line()+geom_point(color="red",size=0.5)+labs(title="Themes Released per year")

```



#Themes

```{r}
set_themes<-themes %>%left_join(sets,by=c("id"="theme_id"))
```


```{r}
set_themes%>%group_by(name.x)%>%summarise(parts_c=sum(num_parts))%>%arrange(desc(parts_c))%>%head(20)%>%ggplot(aes(x=reorder(name.x,parts_c),y=parts_c,fill=name.x,group=1))+geom_line(stat="identity")+geom_point()
```


```{r}
themes_set=set_themes%>%select(name.x,set_num)%>%group_by(name.x)%>%summarise(theme_setcnt=length(unique(set_num)))%>%arrange(desc(theme_setcnt))%>%head(50)
```


```{r}
themes_set%>%head(15)%>%ggplot(aes(x=reorder(name.x,theme_setcnt),theme_setcnt,fill=name.x))+geom_bar(stat="identity")
```

